# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeDvaBoilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeDvaBoilerplate
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'ART',
    'RCTAnimation',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTLinkingIOS',
    'RCTActionSheet',
    'RCTWebSocket', # needed for debugging
    'DevSupport'
    # Add any other subspecs you want to use in your project
    ]
    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

end
